

ALTER TABLE atm DROP CONSTRAINT DF__atm__amount__4316F928;
ALTER TABLE atm ALTER COLUMN amount numeric(38,2);



ALTER TABLE transactions DROP CONSTRAINT FK__transacti__accou__3F466844;

ALTER TABLE users ALTER COLUMN user_id BIGINT;
ALTER TABLE accounts DROP CONSTRAINT FK__accounts__user_i__3A81B327;
ALTER TABLE users DROP CONSTRAINT PK__users__B9BE370FCF4D72BE;
ALTER TABLE users ALTER COLUMN user_id BIGINT;




ALTER TABLE accounts DROP CONSTRAINT DF__accounts__balanc__3B75D760;
ALTER TABLE accounts ALTER COLUMN balance NUMERIC(38, 2);



ALTER TABLE transactions DROP CONSTRAINT UQ__transact__AF91A6AD5BD7D350;
ALTER TABLE transactions DROP CONSTRAINT PK__transact__85C600AFC2540D1F;
ALTER TABLE transactions ALTER COLUMN transaction_id BIGINT;
